### ISSUE TITLE
Force CD32 mode for regular Amiga

### ISSUE THREAD

**Issue by mamejay** [SukkoPera/OpenPSX2AmigaPadAdapter#13]
Hello there.  Great project.  I am just about to finish a board and just realised that you mention the controller switches to CD32 mode automatically when connected to CD32.  Is there a way to force this so can be used in a regular Amiga 500 or 1200 etc?
A lot of games are being ported over using WHDLoad and would be great to used CD32 mode controller.
Thanks and sorry if this is a silly question.

**Comment by mamejay** [comment]
Cancel that.  Built the unit and found it automatically enabled CD32 support.  All good.

**Comment by SukkoPera** [comment]
Yeah, it's the game that tells the joystick to switch to CD32 mode. If it does so, the adapter will just comply. This is supported on all Amiga models AFAIK (not sure about the CDTV with its odd connectors).
