### ISSUE TITLE
it's not an issue just an question

### ISSUE THREAD

**Issue by zambujal** [SukkoPera/OpenPSX2AmigaPadAdapter#17]
I asked about the ressonator and the crystal... but then I read your read.me...  ;)

now I used the ATMEGA 88, there was lag... not with the 328 (I removed the 88, and soldered the 328p) not that many, but annoying. could be an malfunction chip? I wonder...

ha another cup of coffe to you.. for you to give to charity... if you want Sukkopera!
I bought 5 pcb from pcbway.... so I already give one to a friend of mine... ;) that I don't know in person... free of charge! the way this should allways be... FREE or as we portuguese say... GRATIS... is better!

**Comment by zambujal** [comment]
never mind it's working without the ressonator of course and with the 2 caps

**Comment by zambujal** [comment]
thank you for the project sukkopera.. it as a little lag  (0.1 sec) on the amiga 1200... going to try it on amiga cd32
...it's fine it's mostly for adventure games. ;)

**Comment by SukkoPera** [comment]
Sorry, somehow I missed this issue.

I seem to recall we solved this elsewhere, the problem was just the fuses not being set, you should do so with the *Burn Booloader* command before flashing the firmware.

Thanks for your support and enthusiasm about this and my other projects :).
